services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: monster
      MYSQL_DATABASE: monster
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  server:
    build: ./app
    ports:
     - 8080:80
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
  

